import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Selector from '@/components/selector';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header></Header>
        <Selector></Selector>
        <main className='px-6 md:px-12 lg:px-32 py-4'>{children}</main>
      </body>
    </html>
  );
}
